# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('last_submission_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'CronSetting',
                'verbose_name_plural': 'CronSetting',
            },
        ),
    ]
