# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronsetting',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
