# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_identifier', models.CharField(blank=True, max_length=100)),
                ('location_setting_code', models.CharField(blank=True, max_length=60)),
                ('location_type_code', models.CharField(blank=True, max_length=60)),
                ('location_status_code', models.CharField(blank=True, max_length=60)),
                ('current_status_effective_date', models.DateField(blank=True, null=True)),
                ('location_narrative_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_relationship_datetime_range', models.CharField(blank=True, max_length=100)),
                ('location_relationship_type_code', models.CharField(blank=True, max_length=60)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Location Relationship',
                'verbose_name_plural': 'Location Relationships',
            },
        ),
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('district_code', models.CharField(blank=True, max_length=200)),
                ('vdc_code', models.CharField(blank=True, max_length=200)),
                ('ward_no', models.CharField(blank=True, max_length=200)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('property_location', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Physical Location',
                'verbose_name_plural': 'Physical Locations',
            },
        ),
        migrations.CreateModel(
            name='PostalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('address_direction', models.TextField(blank=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Postal Location',
                'verbose_name_plural': 'Postal Locations',
            },
        ),
        migrations.CreateModel(
            name='TelecommunicationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_identification_number', models.CharField(blank=True, max_length=100)),
                ('time_zone', models.CharField(blank=True, max_length=100)),
                ('electronic_address', models.IntegerField(null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'Telecommunication Location',
                'verbose_name_plural': 'Telecommunication Locations',
            },
        ),
        migrations.CreateModel(
            name='VDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdc_code', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('district_code', models.CharField(blank=True, max_length=200)),
                ('layer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'VDC',
                'verbose_name_plural': 'VDCs',
            },
        ),
    ]
