# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Formal Organization',
                'verbose_name_plural': 'Formal Organizations',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.CharField(blank=True, max_length=60)),
                ('sex_code', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
            },
        ),
        migrations.CreateModel(
            name='InformalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type_code', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Informal Organization',
                'verbose_name_plural': 'Informal Organizations',
            },
        ),
        migrations.CreateModel(
            name='NonPersonLivingOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(blank=True, max_length=200)),
                ('species_name', models.CharField(blank=True, max_length=200)),
                ('individual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual')),
            ],
            options={
                'verbose_name': 'Nonperson Living Organism',
                'verbose_name_plural': 'Nonperson Living Organisms',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_identifier', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyLocationParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_datetime_range', models.CharField(blank=True, max_length=100)),
                ('participation_type_code', models.CharField(blank=True, max_length=60)),
                ('current_status_code', models.CharField(blank=True, max_length=60)),
                ('current_status_effective_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
            options={
                'verbose_name': 'Party Location Participation',
                'verbose_name_plural': 'Party Location Participations',
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('party_relationship_type_code', models.CharField(blank=True, max_length=60)),
                ('party_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_relations', to='party.Party')),
                ('party_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_relations_sub', to='party.Party')),
            ],
            options={
                'verbose_name': 'Party Relationship',
                'verbose_name_plural': 'Party Relationships',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('ethnicity_code', models.CharField(blank=True, max_length=60)),
                ('race_code', models.CharField(blank=True, max_length=60)),
                ('occupation_code', models.CharField(blank=True, max_length=60)),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
        migrations.AddField(
            model_name='informalorganization',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organization'),
        ),
        migrations.AddField(
            model_name='individual',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
        migrations.AddField(
            model_name='formalorganization',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organization'),
        ),
    ]
