# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(blank=True, max_length=100)),
                ('morbidity_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'ICD',
                'verbose_name_plural': 'ICDs',
            },
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbidity_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Morbidity',
                'verbose_name_plural': 'Morbidities',
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Outreach',
                'verbose_name_plural': 'Outreaches',
            },
        ),
        migrations.CreateModel(
            name='PatientHA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('sent_date', models.DateField()),
                ('ha_provider_id', models.CharField(blank=True, max_length=100)),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('ward', models.IntegerField()),
                ('obs_k', models.CharField(blank=True, max_length=100)),
                ('obs_l', models.CharField(blank=True, max_length=100)),
                ('obs_m', models.CharField(blank=True, max_length=100)),
                ('derived_n', models.CharField(blank=True, max_length=100)),
                ('derived_o', models.CharField(blank=True, max_length=100)),
                ('derived_p', models.CharField(blank=True, max_length=100)),
                ('derived_q', models.CharField(blank=True, max_length=100)),
                ('derived_r', models.CharField(blank=True, max_length=100)),
                ('derived_s', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='location.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='reports.Group')),
                ('icd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='reports.ICD')),
                ('outreach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='reports.Outreach')),
                ('vdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='location.VDC')),
            ],
        ),
    ]
