# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160710_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientha',
            name='icd',
            field=models.IntegerField(default=0),
        ),
    ]
