# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160717_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientha',
            name='source',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientha',
            name='icd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_has', to='reports.ICD'),
        ),
    ]
