# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160718_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientha',
            name='et',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 4, 26, 18, 738987, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientha',
            name='st',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 4, 26, 37, 843409, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
