# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_identifier', models.CharField(blank=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=100)),
                ('material_type_code', models.CharField(blank=True, max_length=60)),
                ('material_description', models.TextField(blank=True)),
                ('material_datetime_range', models.CharField(blank=True, max_length=100)),
                ('handling_code', models.CharField(blank=True, max_length=60)),
                ('danger_code', models.CharField(blank=True, max_length=60)),
                ('source_site_code', models.CharField(blank=True, max_length=60)),
                ('material_quantity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'verbose_name': 'Material',
            },
        ),
        migrations.CreateModel(
            name='MaterialLocationParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_datetime_range', models.CharField(blank=True, max_length=100)),
                ('participation_type_code', models.CharField(blank=True, max_length=60)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
            ],
            options={
                'verbose_name_plural': 'Material Location Participations',
                'verbose_name': 'Material Location Participation',
            },
        ),
        migrations.CreateModel(
            name='MaterialRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_relationship_type_code', models.CharField(blank=True, max_length=60)),
                ('material_relationship_datetime_range', models.CharField(blank=True, max_length=100)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
            ],
            options={
                'verbose_name_plural': 'Material Relationships',
                'verbose_name': 'Material Relationship',
            },
        ),
        migrations.CreateModel(
            name='MaterialResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_datetime_range', models.CharField(blank=True, max_length=100)),
                ('responsibility_type_code', models.CharField(blank=True, max_length=60)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
            options={
                'verbose_name_plural': 'Material Responsibilities',
                'verbose_name': 'Material Responsibility',
            },
        ),
    ]
