# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('health_activity', '0001_initial'),
        ('material', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type_code', models.CharField(blank=True, max_length=60)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_participations', to='health_activity.HealthActivity')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_participations', to='party.Party')),
            ],
            options={
                'verbose_name_plural': 'Actor Participations',
                'verbose_name': 'Actor Participation',
            },
        ),
        migrations.CreateModel(
            name='TargetParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type_code', models.CharField(blank=True, max_length=60)),
                ('target_awareness_code', models.CharField(blank=True, max_length=60)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_activity.HealthActivity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
            options={
                'verbose_name_plural': 'Target Participations',
                'verbose_name': 'Target Participation',
            },
        ),
    ]
